### ISSUE TITLE
error on playerid if you enter an incorrect value or target is offline (server side)

### ISSUE THREAD

**Issue by dandi83** [esx-framework/esx_basicneeds#13]
put after line 23 this :  if not args.playerId then return xPlayer.showNotification('player offline or wrong value', 'error', 3000) end

**Comment by Mycroft-Studios** [comment]
well yeah, how is this even an Issue xD

of course of you enter a Player that doesnt exist, its going to error, this is just LOGIC

**Comment by Mycroft-Studios** [comment]
also, want to point out, THIS DOESNT EVEN ERROR.

the command handler within ESX already handles this shit.
